version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.dockerfile
    ports:
      - "5001:5001"
    environment:
      - DEBUG=true
      - HOST=0.0.0.0
      - PORT=5001
      - SECRET_KEY=dev-secret-key-change-in-production
      - CORS_ORIGINS=http://localhost:8080
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
